#import <Foundation/Foundation.h>
#import "SWGInlineResponse200.h"
#import "SWGInlineResponse2001.h"
#import "SWGInlineResponse400.h"
#import "SWGApi.h"

/**
* Most Popular API
* Get lists of NYT Articles based on shares, emails, and views.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGDefaultApi: NSObject <SWGApi>

extern NSString* kSWGDefaultApiErrorDomain;
extern NSInteger kSWGDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Most Emailed by Section & Time Period
/// 
///
/// @param section Limits the results by one or more sections. You can use &#x60;all-sections&#x60; or one or more section names seperated by semicolons. See &#x60;viewed/sections.json&#x60; call to get a list of sections.  
/// @param timePeriod Number of days &#x60;1 | 7 | 30 &#x60; corresponds to a day, a week, or a month of content.
/// 
///  code:200 message:"An array of Articles",
///  code:400 message:"",
///  code:403 message:""
///
/// @return SWGInlineResponse2001*
-(NSURLSessionTask*) gETMostemailedSectionTimePeriodJsonWithSection: (NSString*) section
    timePeriod: (NSString*) timePeriod
    completionHandler: (void (^)(SWGInlineResponse2001* output, NSError* error)) handler;


/// Most Shared by Section & Time Period
/// 
///
/// @param section Limits the results by one or more sections. You can use &#x60;all-sections&#x60; or one or more section names seperated by semicolons. See &#x60;viewed/sections.json&#x60; call to get a list of sections.  
/// @param timePeriod Number of days &#x60;1 | 7 | 30 &#x60; corresponds to a day, a week, or a month of content.
/// 
///  code:200 message:"An array of Articles",
///  code:400 message:""
///
/// @return SWGInlineResponse200*
-(NSURLSessionTask*) gETMostsharedSectionTimePeriodJsonWithSection: (NSString*) section
    timePeriod: (NSString*) timePeriod
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;


/// Most Viewed by Section & Time Period
/// 
///
/// @param section Limits the results by one or more sections. You can use &#x60;all-sections&#x60; or one or more section names seperated by semicolons. See &#x60;viewed/sections.json&#x60; call to get a list of sections.  
/// @param timePeriod Number of days &#x60;1 | 7 | 30 &#x60; corresponds to a day, a week, or a month of content.
/// 
///  code:200 message:"An array of Articles"
///
/// @return SWGInlineResponse200*
-(NSURLSessionTask*) gETMostviewedSectionTimePeriodJsonWithSection: (NSString*) section
    timePeriod: (NSString*) timePeriod
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;



@end
