#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Most Popular API
* Get lists of NYT Articles based on shares, emails, and views.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGArticleWithCountTypeMediametadata.h"
@protocol SWGArticleWithCountTypeMediametadata;
@class SWGArticleWithCountTypeMediametadata;



@protocol SWGArticleWithCountTypeMedia
@end

@interface SWGArticleWithCountTypeMedia : SWGObject


@property(nonatomic) NSString* type;

@property(nonatomic) NSString* subtype;

@property(nonatomic) NSString* caption;

@property(nonatomic) NSString* varCopyright;

@property(nonatomic) SWGArticleWithCountTypeMediametadata* mediaMetadata;

@end
