#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Most Popular API
* Get lists of NYT Articles based on shares, emails, and views.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGDesFacet.h"
#import "SWGGeoFacet.h"
#import "SWGOrgFacet.h"
#import "SWGPerFacet.h"

@protocol SWGArticle
@end

@interface SWGArticle : SWGObject


@property(nonatomic) NSString* url;

@property(nonatomic) NSString* column;

@property(nonatomic) NSString* section;

@property(nonatomic) NSString* byline;

@property(nonatomic) NSString* title;

@property(nonatomic) NSString* abstract;

@property(nonatomic) NSString* publishedDate;

@property(nonatomic) NSString* source;

@property(nonatomic) SWGDesFacet* desFacet;

@property(nonatomic) SWGOrgFacet* orgFacet;

@property(nonatomic) SWGPerFacet* perFacet;

@property(nonatomic) SWGGeoFacet* geoFacet;

@end
