#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGArticle.h"
@protocol SWGArticle;
@class SWGArticle;



@protocol SWGInlineResponse200
@end

@interface SWGInlineResponse200 : SWGObject


@property(nonatomic) NSString* status;

@property(nonatomic) NSString* varCopyright;

@property(nonatomic) NSNumber* numResults;

@property(nonatomic) NSArray<SWGArticle>* results;

@end
