#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Most Popular API
* Get lists of NYT Articles based on shares, emails, and views.
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGArticleWithCountType.h"
@protocol SWGArticleWithCountType;
@class SWGArticleWithCountType;



@protocol SWGInlineResponse2001
@end

@interface SWGInlineResponse2001 : SWGObject


@property(nonatomic) NSString* status;

@property(nonatomic) NSString* varCopyright;

@property(nonatomic) NSNumber* numResults;

@property(nonatomic) NSArray<SWGArticleWithCountType>* results;

@end
