#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGArticleWithCountType.h"


@protocol SWGInlineResponse200
@end

@interface SWGInlineResponse200 : SWGObject


@property(nonatomic) NSString* copyright;

@property(nonatomic) NSArray<SWGArticleWithCountType>* results;

@property(nonatomic) NSNumber* numResults;

@property(nonatomic) NSString* status;

@end
